/*
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AccountData
 */
public class AccountDataTest {
    private final AccountData model = new AccountData();

    /**
     * Model tests for AccountData
     */
    @Test
    public void testAccountData() {
        // TODO: test AccountData
    }

    /**
     * Test the property 'unionId'
     */
    @Test
    public void unionIdTest() {
        // TODO: test unionId
    }

    /**
     * Test the property 'isPrivate'
     */
    @Test
    public void isPrivateTest() {
        // TODO: test isPrivate
    }

    /**
     * Test the property 'duetDisabled'
     */
    @Test
    public void duetDisabledTest() {
        // TODO: test duetDisabled
    }

    /**
     * Test the property 'privacyLevels'
     */
    @Test
    public void privacyLevelsTest() {
        // TODO: test privacyLevels
    }

    /**
     * Test the property 'stitchDisabled'
     */
    @Test
    public void stitchDisabledTest() {
        // TODO: test stitchDisabled
    }

    /**
     * Test the property 'commentDisabled'
     */
    @Test
    public void commentDisabledTest() {
        // TODO: test commentDisabled
    }

    /**
     * Test the property 'maxVideoPostDurationSec'
     */
    @Test
    public void maxVideoPostDurationSecTest() {
        // TODO: test maxVideoPostDurationSec
    }

}
