/*
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.DeletePosts200ResponseOneOf;
import org.openapitools.client.model.DeletePosts200ResponseOneOf1;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DeletePosts200Response
 */
public class DeletePosts200ResponseTest {
    private final DeletePosts200Response model = new DeletePosts200Response();

    /**
     * Model tests for DeletePosts200Response
     */
    @Test
    public void testDeletePosts200Response() {
        // TODO: test DeletePosts200Response
    }

    /**
     * Test the property 'deleted'
     */
    @Test
    public void deletedTest() {
        // TODO: test deleted
    }

    /**
     * Test the property 'toTrash'
     */
    @Test
    public void toTrashTest() {
        // TODO: test toTrash
    }

}
