/*
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DeletePosts200ResponseOneOf1
 */
public class DeletePosts200ResponseOneOf1Test {
    private final DeletePosts200ResponseOneOf1 model = new DeletePosts200ResponseOneOf1();

    /**
     * Model tests for DeletePosts200ResponseOneOf1
     */
    @Test
    public void testDeletePosts200ResponseOneOf1() {
        // TODO: test DeletePosts200ResponseOneOf1
    }

    /**
     * Test the property 'toTrash'
     */
    @Test
    public void toTrashTest() {
        // TODO: test toTrash
    }

}
