/*
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VersionOptionsTiktokPrivacyLevel
 */
public class VersionOptionsTiktokPrivacyLevelTest {
    private final VersionOptionsTiktokPrivacyLevel model = new VersionOptionsTiktokPrivacyLevel();

    /**
     * Model tests for VersionOptionsTiktokPrivacyLevel
     */
    @Test
    public void testVersionOptionsTiktokPrivacyLevel() {
        // TODO: test VersionOptionsTiktokPrivacyLevel
    }

    /**
     * Test the property 'account0'
     */
    @Test
    public void account0Test() {
        // TODO: test account0
    }

}
