/*
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.VersionOptionsTiktokPrivacyLevel;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VersionOptionsTiktok
 */
public class VersionOptionsTiktokTest {
    private final VersionOptionsTiktok model = new VersionOptionsTiktok();

    /**
     * Model tests for VersionOptionsTiktok
     */
    @Test
    public void testVersionOptionsTiktok() {
        // TODO: test VersionOptionsTiktok
    }

    /**
     * Test the property 'privacyLevel'
     */
    @Test
    public void privacyLevelTest() {
        // TODO: test privacyLevel
    }

    /**
     * Test the property 'allowComments'
     */
    @Test
    public void allowCommentsTest() {
        // TODO: test allowComments
    }

    /**
     * Test the property 'allowDuet'
     */
    @Test
    public void allowDuetTest() {
        // TODO: test allowDuet
    }

    /**
     * Test the property 'allowStitch'
     */
    @Test
    public void allowStitchTest() {
        // TODO: test allowStitch
    }

    /**
     * Test the property 'contentDisclosure'
     */
    @Test
    public void contentDisclosureTest() {
        // TODO: test contentDisclosure
    }

    /**
     * Test the property 'brandOrganicToggle'
     */
    @Test
    public void brandOrganicToggleTest() {
        // TODO: test brandOrganicToggle
    }

    /**
     * Test the property 'brandContentToggle'
     */
    @Test
    public void brandContentToggleTest() {
        // TODO: test brandContentToggle
    }

}
