/*
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.VersionOptionsInstagram;
import org.openapitools.client.model.VersionOptionsLinkedin;
import org.openapitools.client.model.VersionOptionsMastodon;
import org.openapitools.client.model.VersionOptionsPinterest;
import org.openapitools.client.model.VersionOptionsTiktok;
import org.openapitools.client.model.VersionOptionsYoutube;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VersionOptions
 */
public class VersionOptionsTest {
    private final VersionOptions model = new VersionOptions();

    /**
     * Model tests for VersionOptions
     */
    @Test
    public void testVersionOptions() {
        // TODO: test VersionOptions
    }

    /**
     * Test the property 'tiktok'
     */
    @Test
    public void tiktokTest() {
        // TODO: test tiktok
    }

    /**
     * Test the property 'youtube'
     */
    @Test
    public void youtubeTest() {
        // TODO: test youtube
    }

    /**
     * Test the property 'linkedin'
     */
    @Test
    public void linkedinTest() {
        // TODO: test linkedin
    }

    /**
     * Test the property 'mastodon'
     */
    @Test
    public void mastodonTest() {
        // TODO: test mastodon
    }

    /**
     * Test the property 'instagram'
     */
    @Test
    public void instagramTest() {
        // TODO: test instagram
    }

    /**
     * Test the property 'pinterest'
     */
    @Test
    public void pinterestTest() {
        // TODO: test pinterest
    }

    /**
     * Test the property 'facebookPage'
     */
    @Test
    public void facebookPageTest() {
        // TODO: test facebookPage
    }

}
