/*
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VersionOptionsPinterestBoards
 */
public class VersionOptionsPinterestBoardsTest {
    private final VersionOptionsPinterestBoards model = new VersionOptionsPinterestBoards();

    /**
     * Model tests for VersionOptionsPinterestBoards
     */
    @Test
    public void testVersionOptionsPinterestBoards() {
        // TODO: test VersionOptionsPinterestBoards
    }

    /**
     * Test the property 'accounts0'
     */
    @Test
    public void accounts0Test() {
        // TODO: test accounts0
    }

}
