/*
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package PostPuma;

import PostPuma.ApiException;
import org.openapitools.client.model.DeleteMediaFiles200Response;
import org.openapitools.client.model.DeleteMediaFilesRequest;
import java.io.File;
import org.openapitools.client.model.ListMediaFiles200Response;
import org.openapitools.client.model.MediaFile;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MediaApi
 */
@Disabled
public class MediaApiTest {

    private final MediaApi api = new MediaApi();

    /**
     * Delete media files
     *
     * Delete media files
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteMediaFilesTest() throws ApiException {
        DeleteMediaFilesRequest deleteMediaFilesRequest = null;
        DeleteMediaFiles200Response response = api.deleteMediaFiles(deleteMediaFilesRequest);
        // TODO: test validations
    }

    /**
     * Get media file
     *
     * Get media file
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMediaFileTest() throws ApiException {
        String mediaUuid = null;
        MediaFile response = api.getMediaFile(mediaUuid);
        // TODO: test validations
    }

    /**
     * List media files
     *
     * List media files
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listMediaFilesTest() throws ApiException {
        Integer page = null;
        ListMediaFiles200Response response = api.listMediaFiles(page);
        // TODO: test validations
    }

    /**
     * Upload media file
     *
     * Upload media file
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void uploadMediaFileTest() throws ApiException {
        File _file = null;
        MediaFile response = api.uploadMediaFile(_file);
        // TODO: test validations
    }

}
