/*
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package PostPuma;

import PostPuma.ApiException;
import org.openapitools.client.model.CreateTagRequest;
import org.openapitools.client.model.DeleteMediaFiles200Response;
import org.openapitools.client.model.ListTags200Response;
import org.openapitools.client.model.Tag;
import org.openapitools.client.model.UpdateTagRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TagsApi
 */
@Disabled
public class TagsApiTest {

    private final TagsApi api = new TagsApi();

    /**
     * Create tag
     *
     * Create tag
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTagTest() throws ApiException {
        CreateTagRequest createTagRequest = null;
        Tag response = api.createTag(createTagRequest);
        // TODO: test validations
    }

    /**
     * Delete tag
     *
     * Delete tag
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteTagTest() throws ApiException {
        String tagUuid = null;
        DeleteMediaFiles200Response response = api.deleteTag(tagUuid);
        // TODO: test validations
    }

    /**
     * Get tag
     *
     * Get tag
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTagTest() throws ApiException {
        String tagUuid = null;
        Tag response = api.getTag(tagUuid);
        // TODO: test validations
    }

    /**
     * List tags
     *
     * List tags
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTagsTest() throws ApiException {
        ListTags200Response response = api.listTags();
        // TODO: test validations
    }

    /**
     * Update tag
     *
     * Update tag
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateTagTest() throws ApiException {
        String tagUuid = null;
        UpdateTagRequest updateTagRequest = null;
        DeleteMediaFiles200Response response = api.updateTag(tagUuid, updateTagRequest);
        // TODO: test validations
    }

}
