/*
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.DeletePosts200ResponseOneOf;
import org.openapitools.client.model.DeletePosts200ResponseOneOf1;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import PostPuma.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-24T16:39:28.677807+02:00[Europe/Berlin]", comments = "Generator version: 7.9.0")
public class DeletePosts200Response extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(DeletePosts200Response.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!DeletePosts200Response.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'DeletePosts200Response' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<DeletePosts200ResponseOneOf> adapterDeletePosts200ResponseOneOf = gson.getDelegateAdapter(this, TypeToken.get(DeletePosts200ResponseOneOf.class));
            final TypeAdapter<DeletePosts200ResponseOneOf1> adapterDeletePosts200ResponseOneOf1 = gson.getDelegateAdapter(this, TypeToken.get(DeletePosts200ResponseOneOf1.class));

            return (TypeAdapter<T>) new TypeAdapter<DeletePosts200Response>() {
                @Override
                public void write(JsonWriter out, DeletePosts200Response value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `DeletePosts200ResponseOneOf`
                    if (value.getActualInstance() instanceof DeletePosts200ResponseOneOf) {
                        JsonElement element = adapterDeletePosts200ResponseOneOf.toJsonTree((DeletePosts200ResponseOneOf)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `DeletePosts200ResponseOneOf1`
                    if (value.getActualInstance() instanceof DeletePosts200ResponseOneOf1) {
                        JsonElement element = adapterDeletePosts200ResponseOneOf1.toJsonTree((DeletePosts200ResponseOneOf1)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: DeletePosts200ResponseOneOf, DeletePosts200ResponseOneOf1");
                }

                @Override
                public DeletePosts200Response read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize DeletePosts200ResponseOneOf
                    try {
                        // validate the JSON object to see if any exception is thrown
                        DeletePosts200ResponseOneOf.validateJsonElement(jsonElement);
                        actualAdapter = adapterDeletePosts200ResponseOneOf;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'DeletePosts200ResponseOneOf'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for DeletePosts200ResponseOneOf failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'DeletePosts200ResponseOneOf'", e);
                    }
                    // deserialize DeletePosts200ResponseOneOf1
                    try {
                        // validate the JSON object to see if any exception is thrown
                        DeletePosts200ResponseOneOf1.validateJsonElement(jsonElement);
                        actualAdapter = adapterDeletePosts200ResponseOneOf1;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'DeletePosts200ResponseOneOf1'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for DeletePosts200ResponseOneOf1 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'DeletePosts200ResponseOneOf1'", e);
                    }

                    if (match == 1) {
                        DeletePosts200Response ret = new DeletePosts200Response();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for DeletePosts200Response: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public DeletePosts200Response() {
        super("oneOf", Boolean.FALSE);
    }

    public DeletePosts200Response(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("DeletePosts200ResponseOneOf", DeletePosts200ResponseOneOf.class);
        schemas.put("DeletePosts200ResponseOneOf1", DeletePosts200ResponseOneOf1.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return DeletePosts200Response.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * DeletePosts200ResponseOneOf, DeletePosts200ResponseOneOf1
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof DeletePosts200ResponseOneOf) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof DeletePosts200ResponseOneOf1) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be DeletePosts200ResponseOneOf, DeletePosts200ResponseOneOf1");
    }

    /**
     * Get the actual instance, which can be the following:
     * DeletePosts200ResponseOneOf, DeletePosts200ResponseOneOf1
     *
     * @return The actual instance (DeletePosts200ResponseOneOf, DeletePosts200ResponseOneOf1)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `DeletePosts200ResponseOneOf`. If the actual instance is not `DeletePosts200ResponseOneOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `DeletePosts200ResponseOneOf`
     * @throws ClassCastException if the instance is not `DeletePosts200ResponseOneOf`
     */
    public DeletePosts200ResponseOneOf getDeletePosts200ResponseOneOf() throws ClassCastException {
        return (DeletePosts200ResponseOneOf)super.getActualInstance();
    }
    /**
     * Get the actual instance of `DeletePosts200ResponseOneOf1`. If the actual instance is not `DeletePosts200ResponseOneOf1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `DeletePosts200ResponseOneOf1`
     * @throws ClassCastException if the instance is not `DeletePosts200ResponseOneOf1`
     */
    public DeletePosts200ResponseOneOf1 getDeletePosts200ResponseOneOf1() throws ClassCastException {
        return (DeletePosts200ResponseOneOf1)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to DeletePosts200Response
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with DeletePosts200ResponseOneOf
        try {
            DeletePosts200ResponseOneOf.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for DeletePosts200ResponseOneOf failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with DeletePosts200ResponseOneOf1
        try {
            DeletePosts200ResponseOneOf1.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for DeletePosts200ResponseOneOf1 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format("The JSON string is invalid for DeletePosts200Response with oneOf schemas: DeletePosts200ResponseOneOf, DeletePosts200ResponseOneOf1. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of DeletePosts200Response given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of DeletePosts200Response
     * @throws IOException if the JSON string is invalid with respect to DeletePosts200Response
     */
    public static DeletePosts200Response fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, DeletePosts200Response.class);
    }

    /**
     * Convert an instance of DeletePosts200Response to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

