/*
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import PostPuma.JSON;

/**
 * DeletePosts200ResponseOneOf1
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-24T16:39:28.677807+02:00[Europe/Berlin]", comments = "Generator version: 7.9.0")
public class DeletePosts200ResponseOneOf1 {
  public static final String SERIALIZED_NAME_TO_TRASH = "to_trash";
  @SerializedName(SERIALIZED_NAME_TO_TRASH)
  private Boolean toTrash;

  public DeletePosts200ResponseOneOf1() {
  }

  public DeletePosts200ResponseOneOf1 toTrash(Boolean toTrash) {
    this.toTrash = toTrash;
    return this;
  }

  /**
   * Get toTrash
   * @return toTrash
   */
  @javax.annotation.Nullable
  public Boolean getToTrash() {
    return toTrash;
  }

  public void setToTrash(Boolean toTrash) {
    this.toTrash = toTrash;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeletePosts200ResponseOneOf1 deletePosts200ResponseOneOf1 = (DeletePosts200ResponseOneOf1) o;
    return Objects.equals(this.toTrash, deletePosts200ResponseOneOf1.toTrash);
  }

  @Override
  public int hashCode() {
    return Objects.hash(toTrash);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeletePosts200ResponseOneOf1 {\n");
    sb.append("    toTrash: ").append(toIndentedString(toTrash)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("to_trash");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DeletePosts200ResponseOneOf1
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DeletePosts200ResponseOneOf1.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DeletePosts200ResponseOneOf1 is not found in the empty JSON string", DeletePosts200ResponseOneOf1.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DeletePosts200ResponseOneOf1.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DeletePosts200ResponseOneOf1` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DeletePosts200ResponseOneOf1.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DeletePosts200ResponseOneOf1' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DeletePosts200ResponseOneOf1> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DeletePosts200ResponseOneOf1.class));

       return (TypeAdapter<T>) new TypeAdapter<DeletePosts200ResponseOneOf1>() {
           @Override
           public void write(JsonWriter out, DeletePosts200ResponseOneOf1 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DeletePosts200ResponseOneOf1 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DeletePosts200ResponseOneOf1 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DeletePosts200ResponseOneOf1
   * @throws IOException if the JSON string is invalid with respect to DeletePosts200ResponseOneOf1
   */
  public static DeletePosts200ResponseOneOf1 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DeletePosts200ResponseOneOf1.class);
  }

  /**
   * Convert an instance of DeletePosts200ResponseOneOf1 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

