/*
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.VersionOptionsTiktokPrivacyLevel;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import PostPuma.JSON;

/**
 * VersionOptionsTiktok
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-24T16:39:28.677807+02:00[Europe/Berlin]", comments = "Generator version: 7.9.0")
public class VersionOptionsTiktok {
  public static final String SERIALIZED_NAME_PRIVACY_LEVEL = "privacy_level";
  @SerializedName(SERIALIZED_NAME_PRIVACY_LEVEL)
  private VersionOptionsTiktokPrivacyLevel privacyLevel;

  public static final String SERIALIZED_NAME_ALLOW_COMMENTS = "allow_comments";
  @SerializedName(SERIALIZED_NAME_ALLOW_COMMENTS)
  private VersionOptionsTiktokPrivacyLevel allowComments;

  public static final String SERIALIZED_NAME_ALLOW_DUET = "allow_duet";
  @SerializedName(SERIALIZED_NAME_ALLOW_DUET)
  private VersionOptionsTiktokPrivacyLevel allowDuet;

  public static final String SERIALIZED_NAME_ALLOW_STITCH = "allow_stitch";
  @SerializedName(SERIALIZED_NAME_ALLOW_STITCH)
  private VersionOptionsTiktokPrivacyLevel allowStitch;

  public static final String SERIALIZED_NAME_CONTENT_DISCLOSURE = "content_disclosure";
  @SerializedName(SERIALIZED_NAME_CONTENT_DISCLOSURE)
  private VersionOptionsTiktokPrivacyLevel contentDisclosure;

  public static final String SERIALIZED_NAME_BRAND_ORGANIC_TOGGLE = "brand_organic_toggle";
  @SerializedName(SERIALIZED_NAME_BRAND_ORGANIC_TOGGLE)
  private VersionOptionsTiktokPrivacyLevel brandOrganicToggle;

  public static final String SERIALIZED_NAME_BRAND_CONTENT_TOGGLE = "brand_content_toggle";
  @SerializedName(SERIALIZED_NAME_BRAND_CONTENT_TOGGLE)
  private VersionOptionsTiktokPrivacyLevel brandContentToggle;

  public VersionOptionsTiktok() {
  }

  public VersionOptionsTiktok privacyLevel(VersionOptionsTiktokPrivacyLevel privacyLevel) {
    this.privacyLevel = privacyLevel;
    return this;
  }

  /**
   * Get privacyLevel
   * @return privacyLevel
   */
  @javax.annotation.Nullable
  public VersionOptionsTiktokPrivacyLevel getPrivacyLevel() {
    return privacyLevel;
  }

  public void setPrivacyLevel(VersionOptionsTiktokPrivacyLevel privacyLevel) {
    this.privacyLevel = privacyLevel;
  }


  public VersionOptionsTiktok allowComments(VersionOptionsTiktokPrivacyLevel allowComments) {
    this.allowComments = allowComments;
    return this;
  }

  /**
   * Get allowComments
   * @return allowComments
   */
  @javax.annotation.Nullable
  public VersionOptionsTiktokPrivacyLevel getAllowComments() {
    return allowComments;
  }

  public void setAllowComments(VersionOptionsTiktokPrivacyLevel allowComments) {
    this.allowComments = allowComments;
  }


  public VersionOptionsTiktok allowDuet(VersionOptionsTiktokPrivacyLevel allowDuet) {
    this.allowDuet = allowDuet;
    return this;
  }

  /**
   * Get allowDuet
   * @return allowDuet
   */
  @javax.annotation.Nullable
  public VersionOptionsTiktokPrivacyLevel getAllowDuet() {
    return allowDuet;
  }

  public void setAllowDuet(VersionOptionsTiktokPrivacyLevel allowDuet) {
    this.allowDuet = allowDuet;
  }


  public VersionOptionsTiktok allowStitch(VersionOptionsTiktokPrivacyLevel allowStitch) {
    this.allowStitch = allowStitch;
    return this;
  }

  /**
   * Get allowStitch
   * @return allowStitch
   */
  @javax.annotation.Nullable
  public VersionOptionsTiktokPrivacyLevel getAllowStitch() {
    return allowStitch;
  }

  public void setAllowStitch(VersionOptionsTiktokPrivacyLevel allowStitch) {
    this.allowStitch = allowStitch;
  }


  public VersionOptionsTiktok contentDisclosure(VersionOptionsTiktokPrivacyLevel contentDisclosure) {
    this.contentDisclosure = contentDisclosure;
    return this;
  }

  /**
   * Get contentDisclosure
   * @return contentDisclosure
   */
  @javax.annotation.Nullable
  public VersionOptionsTiktokPrivacyLevel getContentDisclosure() {
    return contentDisclosure;
  }

  public void setContentDisclosure(VersionOptionsTiktokPrivacyLevel contentDisclosure) {
    this.contentDisclosure = contentDisclosure;
  }


  public VersionOptionsTiktok brandOrganicToggle(VersionOptionsTiktokPrivacyLevel brandOrganicToggle) {
    this.brandOrganicToggle = brandOrganicToggle;
    return this;
  }

  /**
   * Get brandOrganicToggle
   * @return brandOrganicToggle
   */
  @javax.annotation.Nullable
  public VersionOptionsTiktokPrivacyLevel getBrandOrganicToggle() {
    return brandOrganicToggle;
  }

  public void setBrandOrganicToggle(VersionOptionsTiktokPrivacyLevel brandOrganicToggle) {
    this.brandOrganicToggle = brandOrganicToggle;
  }


  public VersionOptionsTiktok brandContentToggle(VersionOptionsTiktokPrivacyLevel brandContentToggle) {
    this.brandContentToggle = brandContentToggle;
    return this;
  }

  /**
   * Get brandContentToggle
   * @return brandContentToggle
   */
  @javax.annotation.Nullable
  public VersionOptionsTiktokPrivacyLevel getBrandContentToggle() {
    return brandContentToggle;
  }

  public void setBrandContentToggle(VersionOptionsTiktokPrivacyLevel brandContentToggle) {
    this.brandContentToggle = brandContentToggle;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VersionOptionsTiktok versionOptionsTiktok = (VersionOptionsTiktok) o;
    return Objects.equals(this.privacyLevel, versionOptionsTiktok.privacyLevel) &&
        Objects.equals(this.allowComments, versionOptionsTiktok.allowComments) &&
        Objects.equals(this.allowDuet, versionOptionsTiktok.allowDuet) &&
        Objects.equals(this.allowStitch, versionOptionsTiktok.allowStitch) &&
        Objects.equals(this.contentDisclosure, versionOptionsTiktok.contentDisclosure) &&
        Objects.equals(this.brandOrganicToggle, versionOptionsTiktok.brandOrganicToggle) &&
        Objects.equals(this.brandContentToggle, versionOptionsTiktok.brandContentToggle);
  }

  @Override
  public int hashCode() {
    return Objects.hash(privacyLevel, allowComments, allowDuet, allowStitch, contentDisclosure, brandOrganicToggle, brandContentToggle);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VersionOptionsTiktok {\n");
    sb.append("    privacyLevel: ").append(toIndentedString(privacyLevel)).append("\n");
    sb.append("    allowComments: ").append(toIndentedString(allowComments)).append("\n");
    sb.append("    allowDuet: ").append(toIndentedString(allowDuet)).append("\n");
    sb.append("    allowStitch: ").append(toIndentedString(allowStitch)).append("\n");
    sb.append("    contentDisclosure: ").append(toIndentedString(contentDisclosure)).append("\n");
    sb.append("    brandOrganicToggle: ").append(toIndentedString(brandOrganicToggle)).append("\n");
    sb.append("    brandContentToggle: ").append(toIndentedString(brandContentToggle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("privacy_level");
    openapiFields.add("allow_comments");
    openapiFields.add("allow_duet");
    openapiFields.add("allow_stitch");
    openapiFields.add("content_disclosure");
    openapiFields.add("brand_organic_toggle");
    openapiFields.add("brand_content_toggle");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to VersionOptionsTiktok
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!VersionOptionsTiktok.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in VersionOptionsTiktok is not found in the empty JSON string", VersionOptionsTiktok.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!VersionOptionsTiktok.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `VersionOptionsTiktok` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `privacy_level`
      if (jsonObj.get("privacy_level") != null && !jsonObj.get("privacy_level").isJsonNull()) {
        VersionOptionsTiktokPrivacyLevel.validateJsonElement(jsonObj.get("privacy_level"));
      }
      // validate the optional field `allow_comments`
      if (jsonObj.get("allow_comments") != null && !jsonObj.get("allow_comments").isJsonNull()) {
        VersionOptionsTiktokPrivacyLevel.validateJsonElement(jsonObj.get("allow_comments"));
      }
      // validate the optional field `allow_duet`
      if (jsonObj.get("allow_duet") != null && !jsonObj.get("allow_duet").isJsonNull()) {
        VersionOptionsTiktokPrivacyLevel.validateJsonElement(jsonObj.get("allow_duet"));
      }
      // validate the optional field `allow_stitch`
      if (jsonObj.get("allow_stitch") != null && !jsonObj.get("allow_stitch").isJsonNull()) {
        VersionOptionsTiktokPrivacyLevel.validateJsonElement(jsonObj.get("allow_stitch"));
      }
      // validate the optional field `content_disclosure`
      if (jsonObj.get("content_disclosure") != null && !jsonObj.get("content_disclosure").isJsonNull()) {
        VersionOptionsTiktokPrivacyLevel.validateJsonElement(jsonObj.get("content_disclosure"));
      }
      // validate the optional field `brand_organic_toggle`
      if (jsonObj.get("brand_organic_toggle") != null && !jsonObj.get("brand_organic_toggle").isJsonNull()) {
        VersionOptionsTiktokPrivacyLevel.validateJsonElement(jsonObj.get("brand_organic_toggle"));
      }
      // validate the optional field `brand_content_toggle`
      if (jsonObj.get("brand_content_toggle") != null && !jsonObj.get("brand_content_toggle").isJsonNull()) {
        VersionOptionsTiktokPrivacyLevel.validateJsonElement(jsonObj.get("brand_content_toggle"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!VersionOptionsTiktok.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'VersionOptionsTiktok' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<VersionOptionsTiktok> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(VersionOptionsTiktok.class));

       return (TypeAdapter<T>) new TypeAdapter<VersionOptionsTiktok>() {
           @Override
           public void write(JsonWriter out, VersionOptionsTiktok value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public VersionOptionsTiktok read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of VersionOptionsTiktok given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of VersionOptionsTiktok
   * @throws IOException if the JSON string is invalid with respect to VersionOptionsTiktok
   */
  public static VersionOptionsTiktok fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, VersionOptionsTiktok.class);
  }

  /**
   * Convert an instance of VersionOptionsTiktok to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

