/*
 * PostPuma - OpenAPI 3.0
 * PostPuma API specifications
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@postpuma.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import PostPuma.JSON;

/**
 * VersionOptionsPinterestBoards
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-24T16:39:28.677807+02:00[Europe/Berlin]", comments = "Generator version: 7.9.0")
public class VersionOptionsPinterestBoards {
  public static final String SERIALIZED_NAME_ACCOUNTS0 = "accounts-0";
  @SerializedName(SERIALIZED_NAME_ACCOUNTS0)
  private String accounts0;

  public VersionOptionsPinterestBoards() {
  }

  public VersionOptionsPinterestBoards accounts0(String accounts0) {
    this.accounts0 = accounts0;
    return this;
  }

  /**
   * Get accounts0
   * @return accounts0
   */
  @javax.annotation.Nullable
  public String getAccounts0() {
    return accounts0;
  }

  public void setAccounts0(String accounts0) {
    this.accounts0 = accounts0;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VersionOptionsPinterestBoards versionOptionsPinterestBoards = (VersionOptionsPinterestBoards) o;
    return Objects.equals(this.accounts0, versionOptionsPinterestBoards.accounts0);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accounts0);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VersionOptionsPinterestBoards {\n");
    sb.append("    accounts0: ").append(toIndentedString(accounts0)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("accounts-0");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to VersionOptionsPinterestBoards
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!VersionOptionsPinterestBoards.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in VersionOptionsPinterestBoards is not found in the empty JSON string", VersionOptionsPinterestBoards.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!VersionOptionsPinterestBoards.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `VersionOptionsPinterestBoards` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("accounts-0") != null && !jsonObj.get("accounts-0").isJsonNull()) && !jsonObj.get("accounts-0").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `accounts-0` to be a primitive type in the JSON string but got `%s`", jsonObj.get("accounts-0").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!VersionOptionsPinterestBoards.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'VersionOptionsPinterestBoards' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<VersionOptionsPinterestBoards> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(VersionOptionsPinterestBoards.class));

       return (TypeAdapter<T>) new TypeAdapter<VersionOptionsPinterestBoards>() {
           @Override
           public void write(JsonWriter out, VersionOptionsPinterestBoards value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public VersionOptionsPinterestBoards read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of VersionOptionsPinterestBoards given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of VersionOptionsPinterestBoards
   * @throws IOException if the JSON string is invalid with respect to VersionOptionsPinterestBoards
   */
  public static VersionOptionsPinterestBoards fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, VersionOptionsPinterestBoards.class);
  }

  /**
   * Convert an instance of VersionOptionsPinterestBoards to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

